import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import NavbarLayout from "@/components/navbar/NavbarLayout";
import FooterLayout from "@/components/footer/FooterLayout";
const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  weight: ["400", "700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale == "en" ? "ltr" : "rtl"} className="scroll-smooth">
      <body className={tajawal.className}>
        <NextIntlClientProvider messages={messages}>
          <div className="bg-gray-100">
            <NavbarLayout />
            <div className="container">{children}</div>
            <FooterLayout/>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
